bot:
  token: <your token>
  description: "\uD83D\uDC32 DragonBot {version}"
serverconfig:
  server:
  channels:
    glowny:
    rejestracja:
    rejestracja_pomoc:
    przenoszenie_rang:
    zmiana_nicku:
    zgloszenia_s12:
    zgloszenia_s16:
    bot:
    banykicki:
    wiadpotw:
    zgloszenia:
    propozycje:
    role:
    colors:
    ogloszenia:
    zmiany:
    eventy:
    testowy:
    logi:
  voicechannels:
    prywatne:
  categories:
    prywatne:
    zgl_otwarte:
    zgl_zamkniete:
    propo_otwarte:
    propo_zamkniete:
  emojis:
    plus_jeden:
    minus_jeden:
    plus_jeden_name: "oj_tak_plus_jeden"
    minus_jeden_name: "oj_nie_minus_jeden"
  roles:
    gracz:
    vip:
    svip:
    mvip:
    evip:
    pomocnik:
    moderator:
    viceadministrator:
    administrator:
    opiekun:
    wlasciciel:
    rola_ogloszenia:
    rola_eventy:
    rola_zmiany:
    rola_wyciszony:
    colors:
      default_pink:
      blue:
      green:
      yellow:
      orange:
      purple:
      grey:
      black:
      white:
report_sound: BLOCK_ANVIL_LAND
embeds:
  footer:
    text: "DragonBot {version} â€¢ {time}"
    icon: "http://dcrft.pl/uploads/5bb8d859bb152e08470e24f2/dclogo3_shadow_alpha.png"
  reports:
    author: "ZgÅ‚oszenia"
    field:
      name: "Aby utworzyÄ‡ zgÅ‚oszenie, kliknij przycisk."
      value: "Zostanie utworzony nowy kanaÅ‚ zgÅ‚oszenia."
    button:
      id: "new_report"
      label: "UtwÃ³rz zgÅ‚oszenie"
    new_report:
      author: "ZgÅ‚oszenie #"
      field1:
        name: "CzeÅ›Ä‡! DziÄ™kujemy za otwarcie zgÅ‚oszenia."
        value: "Opisz tu swÃ³j problem. Postaramy siÄ™ odpowiedzieÄ‡ jak najszybciej!"
      field2:
        name: "Chcesz zamknÄ…Ä‡ zgÅ‚oszenie?"
        value: "UÅ¼yj przycisku"
      button:
        id: "close_report"
        label: "Zamknij zgÅ‚oszenie"
        closed:
          id: "report_closed"
          label: "ZgÅ‚oszenie zamkniÄ™te"
      channel_name: "âŸ¨â—âŸ©zgloszenie-"
  suggestions:
    author: "Propozycje"
    field:
      name: "Aby utworzyÄ‡ propozycjÄ™, kliknij przycisk."
      value: "Zostanie utworzony nowy kanaÅ‚ propozycji."
    button:
      id: "success"
      label: "UtwÃ³rz propozycjÄ™"
    new_suggestion:
      author: "Propozycja #"
      field1:
        name: "CzeÅ›Ä‡! DziÄ™kujemy za utworzenie propozycji."
        value: "Opisz tu swojÄ… sugestiÄ™. Postaramy siÄ™ odpowiedzieÄ‡ jak najszybciej!"
      field2:
        name: "Propozycja jest widoczna dla kaÅ¼dego."
        value: "Administracja moÅ¼e jÄ… odrzuciÄ‡ bÄ…dÅº zaakceptowaÄ‡."
      button_accept:
        id: "accept_suggestion"
        label: "Zaakceptuj propozycjÄ™"
        closed:
          id: "report_closed"
          label: "Propozycja zaakceptowana"
      button_reject:
        id: "reject_suggestion"
        label: "OdrzuÄ‡ propozycjÄ™"
        closed:
          id: "report_closed"
          label: "Propozycja odrzucona"
      button_close:
        id: "close_suggestion"
        label: "Zamknij propozycjÄ™"
        closed:
          id: "report_closed"
          label: "Propozycja zamkniÄ™ta"
      accepted: "Propozycja zostaÅ‚a zaakceptowana przez"
      rejected: "Propozycja zostaÅ‚a odrzucona przez"
      closed: "Propozycja zostaÅ‚a zamkniÄ™ta przez"
      channel_name: "âŸ¨ğŸ‰âŸ©propozycja-"
  roles:
    author: "Wzmianki"
    field:
      name: "Wybierz rolÄ™/e dotyczÄ…cÄ…/e wzmianek."
      value: "Kliknij w menu poniÅ¼ej"
  colors:
    author: "Kolory"
    field:
      name: "Wybierz kolor pseudonimu."
      value: "Kliknij w menu poniÅ¼ej"
punishments:
  default_reason: "brak powodu"